---
- name: CREATE ROLE {{ postgresql_app_user }}
  community.postgresql.postgresql_user:
    name: "{{ postgresql_app_user }}"
    password: "{{ postgresql_app_user_password }}"
    role_attr_flags: NOCREATEDB,NOSUPERUSER,NOCREATEROLE
    login_password: "{{ postgresql_login_password }}"
    login_user: "{{ postgresql_login_user }}"
  environment:
    PGOPTIONS: "-c password_encryption=scram-sha-256"

- name: CREATE DATABASE {{ postgresql_app_database }}
  community.postgresql.postgresql_db:
    name: "{{ postgresql_app_database }}"
    owner: "{{ postgresql_app_user }}"
    login_password: "{{ postgresql_login_password }}"
    login_user: "{{ postgresql_login_user }}"

- name: GRANT ALL ON DATABASE {{ postgresql_app_database }} TO {{ postgresql_app_user }}
  community.postgresql.postgresql_privs:
    db: "{{ postgresql_app_database }}"
    privs: ALL
    type: database
    role: "{{ postgresql_app_user }}"
    login_password: "{{ postgresql_login_password }}"
    login_user: "{{ postgresql_login_user }}"
