---
ansible_user: "rev"

zfs_scrub_pools:
  - "serenity"

zfs_trim_pools:
  - serenity

# First saturday and sunday of the month.
zfs_scrub_schedule: "Sat *-*-1..7 09:00"
zfs_trim_schedule: "Sun *-*-1..7 09:00"
