---
ansible_user: "rev"

zfs_scrub_pools:
  - "serenity"

zfs_trim_pools:
  - "serenity"

zfs_scrub_schedule: "Sat *-*-* 09:00"
zfs_trim_schedule: "Sat *-*-* 09:00"

sysctl_vars:
  - name: "net.core.rmem_max"
    value: 7500000
  - name: "net.core.wmem_max"
    value: 7500000
