---
ansible_user: "rev"

zfs_scrub_pools:
  - "serenity"

zfs_trim_pools:
  - "serenity"

zfs_scrub_schedule: "Sat *-*-* 09:00"
zfs_trim_schedule: "Sat *-*-* 09:00"

sysctl_vars:
  - name: "vm.swappiness"
    value: 180
  - name: "vm.watermark_boost_factor"
    value: 0
  - name: "vm.watermark_scale_factor"
    value: 125
  - name: "vm.page-cluster"
    value: 0
  - name: "net.core.rmem_max"
    value: 4194304
  - name: "net.core.wmem_max"
    value: 4194304
  - name: "net.ipv4.icmp_echo_ignore_broadcasts"
    value: 1
  - name: "net.ipv4.conf.default.rp_filter"
    value: 1
  - name: "net.ipv4.conf.all.rp_filter"
    value: 1
  - name: "net.ipv4.ip_forward"
    value: 0
  - name: "fs.inotify.max_user_watches"
    value: 524288
