---
- name: "systemd:systemd|daemon-reexec"
  ansible.builtin.systemd:
    daemon_reexec: true

- name: "systemd:journald|restart"
  ansible.builtin.service:
    name: "systemd-journald"
    state: "restarted"

- name: "systemd:resolved|restart"
  ansible.builtin.service:
    name: "systemd-resolved"
    state: "restarted"
