---
- name: Check to see if the selected version of Poetry is already installed
  stat:
    path: "{{ poetry_tmp_dir }}/install-poetry.{{ poetry_version }}.py"
  register: stat_result

- name: Get setup script
  get_url:
    url: https://install.python-poetry.org
    dest: "{{ poetry_tmp_dir }}/install-poetry.{{ poetry_version }}.py"
  when: not stat_result.stat.exists

- name: Install to {{ poetry_home }}
  command: python {{ poetry_tmp_dir }}/install-poetry.{{ poetry_version }}.py
  environment:
    POETRY_VERSION: "{{ poetry_version }}"
    POETRY_HOME: "{{ poetry_home }}"
    POETRY_NO_INTERACTION: "1"
  when: not stat_result.stat.exists

- name: Set world-readable permissions
  file:
    path: "{{ poetry_home }}"
    mode: u=rwX,g=rX,o=rX
    recurse: yes

- name: Set executable permissions
  file:
    path: "{{ poetry_home }}/bin/poetry"
    state: file
    mode: a+x

- name: Create /usr/local/bin symlink
  file:
    src: "{{ poetry_home }}/bin/poetry"
    path: /usr/local/bin/poetry
    state: link
