repos:
  - repo: local
    hooks:
      - id: end-of-file-fixer
        name: end-of-file-fixer
        entry: end-of-file-fixer
        language: system
        types: [text]

      - id: trailing-whitespace-fixer
        name: trailing-whitespace-fixer
        entry: trailing-whitespace-fixer
        language: system
        types: [text]

      - id: check-yaml
        name: check-yaml
        entry: check-yaml
        args: [--unsafe]
        language: system
        types: [yaml]

      - id: check-shebang-scripts-are-executable
        name: check-shebang-scripts-are-executable
        entry: check-shebang-scripts-are-executable
        language: system
        types: [text]

      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]

      - id: ansible-lint
        name: ansible-lint
        entry: ansible-lint
        language: system
        types: [text]
        pass_filenames: false
        always_run: true
