---
- name: Apply common configuration to all nodes
  hosts: all
  roles:
    - common
    - sysctl

- name: Set up msmtp as default mta
  hosts: all
  roles:
    - msmtp

# - name: initramfs hooks
#   hosts:
#     - phoenix
#   roles:
#     - systemd-boot
#     - kernel-hooks

- name: Set up ZFS maintenance
  hosts: zfs
  roles:
    - zfs-maintenance
