---
- name: Apply common configuration to all nodes
  hosts: all
  roles:
    - role: common

- name: Set up ZFS maintenance
  hosts: zfs
  roles:
    - role: zfs-maintenance

- name: Set up msmtp as default mta
  hosts: all
  roles:
    - role: msmtp
