---
- name: Apply common configuration to all nodes
  hosts: all
  roles:
    - common

- name: Set up msmtp as default mta
  hosts: all
  roles:
    - msmtp

- name: Set up Telegraf
  hosts:
    - luna
    - vms
  roles:
    - telegraf

- name: initramfs hooks
  hosts:
    - phoenix
  roles:
    - systemd-boot
    - kernel-hooks

- name: Set up ZFS maintenance
  hosts: zfs
  roles:
    - zfs-maintenance
