---
- name: Apply common configuration to all nodes
  hosts: all
  roles:
    - role: common
      tags: common

- name: Deploy gentoogram-bot
  hosts: luna
  roles:
    - role: gentoogram
      tags: gentoogram

- name: Deploy pste
  hosts: luna
  roles:
    - role: pste
      tags: pste
