---
- name: Speedtest
  hosts: all

  tasks:
    - name: Get speedtest script
      get_url:
        url: https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py
        dest: /tmp/ansible-speedtest

    - name: Run speedtest
      command: python3 /tmp/ansible-speedtest --simple
      register: output
      changed_when: false

    - name: Results
      debug:
        msg: "{{ output.stdout_lines }}"
