---
- name: Speedtest
  hosts: all

  tasks:
    - name: Get speedtest script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py
        dest: /tmp/ansible-speedtest
        mode: 644

    - name: Run speedtest
      ansible.builtin.command:
        cmd: python3 /tmp/ansible-speedtest --simple --secure
      register: output
      changed_when: false

    - name: Results
      ansible.builtin.debug:
        msg: "{{ output.stdout_lines }}"
