---
all:
  hosts:
    serenity:
      ansible_connection: local
    luna:
      ansible_host: luna.lwatson.dev
    ark:
      ansible_host: ark.lwatson.dev
    phoenix:
      ansible_host: phoenix.notoriousdev.com
    nova:
      ansible_host: nova.ark.wg
    monitor:
      ansible_host: monitor.lwatson.dev
  children:
    ndev:
      hosts:
        phoenix:
    workstations:
      hosts:
        serenity:
        nova:
    servers:
      hosts:
        luna:
        phoenix:
    vms:
      hosts:
        ark:
        monitor:
    zfs:
      hosts:
        luna:
        phoenix:
        serenity:
        nova:
