---
all:
  hosts:
    serenity:
      ansible_connection: "local"
    luna:
      ansible_host: "luna.lwatson.dev"
    nova:
      ansible_host: "nova.hedgehog-skate.ts.net"
    monitor:
      ansible_host: "monitor.lwatson.dev"
    netmon:
      ansible_user: "root"
      ansible_host: "netmon.hedgehog-skate.ts.net"
    pve:
      ansible_user: "root"
      ansible_host: "192.168.68.57"

  children:
    workstations:
      hosts:
        serenity:
        nova:
    servers:
      hosts:
        luna:
        monitor:
        pve:
    vms:
      hosts:
        monitor:
    zfs:
      hosts:
        luna:
        serenity:
        nova:
        pve:
    debian:
      hosts:
        monitor:
        netmon:
        pve:
