---
all:
  hosts:
    serenity:
      ansible_connection: local
    luna:
      ansible_host: luna.lwatson.dev
    ark:
      ansible_host: ark.lwatson.dev
    nova:
      ansible_host: nova.ark.wg
    monitor:
      ansible_host: monitor.lwatson.dev
    pi-netmon:
      ansible_host: pi-netmon.ark.wg
  children:
    workstations:
      hosts:
        serenity:
        nova:
    servers:
      hosts:
        luna:
        ark:
        monitor:
    vms:
      hosts:
        ark:
        monitor:
    zfs:
      hosts:
        luna:
        serenity:
        nova:
