---
all:
  hosts:
    serenity:
      ansible_connection: "local"
    luna:
      ansible_host: "luna.lwatson.dev"
    # nova:
    #   ansible_host: "nova.hedgehog-skate.ts.net"
    monitor:
      ansible_host: "monitor.lwatson.dev"
    ntfy:
      ansible_user: "root"
      ansible_host: "ntfy.lwatson.dev"
    pve:
      ansible_user: "root"
      ansible_host: "pve.internal.home.lwatson.dev"
    pve-router:
      ansible_user: "root"
      ansible_host: "pve-router.hedgehog-skate.ts.net"
    pve-netmon:
      ansible_user: "root"
      ansible_host: "pve-netmon.hedgehog-skate.ts.net"
    pve-caddy:
      ansible_user: "root"
      ansible_host: "caddy.internal.home.lwatson.dev"
    pve-vaultwarden:
      ansible_user: "root"
      ansible_host: "vaultwarden.internal.home.lwatson.dev"
    pve-postgresql:
      ansible_user: "root"
      ansible_host: "postgresql.internal.home.lwatson.dev"
    pve-mqtt:
      ansible_user: "root"
      ansible_host: "mqtt.internal.home.lwatson.dev"
    pve-zigbee2mqtt:
      ansible_user: "root"
      ansible_host: "zigbee2mqtt.internal.home.lwatson.dev"
    pve-frigate:
      ansible_user: "root"
      ansible_host: "frigate.internal.home.lwatson.dev"

  children:
    workstations:
      hosts:
        serenity:
        # nova:
    servers:
      hosts:
        luna:
        monitor:
        pve:
        ntfy:
    vms:
      hosts:
        monitor:
        ntfy:
        pve-frigate:
        pve-vaultwarden:
    zfs:
      hosts:
        luna:
        serenity:
        # nova:
        pve:
    debian:
      hosts:
        monitor:
        ntfy:
        pve:
        pve-router:
        pve-netmon:
        pve-caddy:
        pve-vaultwarden:
        pve-postgresql:
        pve-mqtt:
        pve-zigbee2mqtt:
        pve-frigate:
    lxc:
      hosts:
        pve-router:
        pve-netmon:
        pve-caddy:
        pve-postgresql:
        pve-mqtt:
        pve-zigbee2mqtt:
    pveguests:
      hosts:
        pve-router:
        pve-netmon:
        pve-caddy:
        pve-postgresql:
        pve-mqtt:
        pve-zigbee2mqtt:
        pve-frigate:
        pve-vaultwarden:
