---
all:
  hosts:
    serenity:
      ansible_connection: local
    luna:
      ansible_host: luna.lwatson.dev
    nova:
      ansible_host: nova.hedgehog-skate.ts.net
    monitor:
      ansible_host: monitor.lwatson.dev
    pi-netmon:
      ansible_host: pi-netmon.hedgehog-skate.ts.net
    pi-desktop:
      ansible_host: pi-desktop.hedgehog-skate.ts.net
  children:
    workstations:
      hosts:
        serenity:
        nova:
    servers:
      hosts:
        luna:
        monitor:
    vms:
      hosts:
        monitor:
    zfs:
      hosts:
        luna:
        serenity:
        nova:
