---
all:
  hosts:
    serenity:
      ansible_connection: "local"
    luna:
      ansible_host: "luna.lwatson.dev"
    nova:
      ansible_host: "nova.hedgehog-skate.ts.net"
    monitor:
      ansible_host: "monitor.lwatson.dev"
    pve:
      ansible_user: "root"
      ansible_host: "pve"
    pve-router:
      ansible_user: "root"
      ansible_host: "pve-router"
    netmon:
      ansible_user: "root"
      ansible_host: "pve-netmon"
    caddy:
      ansible_user: "root"
      ansible_host: "pve-caddy"
    vaultwarden:
      ansible_user: "root"
      ansible_host: "pve-vaultwarden"
    postgresql:
      ansible_user: "root"
      ansible_host: "pve-postgresql"
    mqtt:
      ansible_user: "root"
      ansible_host: "pve-mqtt"
    zigbee2mqtt:
      ansible_user: "root"
      ansible_host: "pve-zigbee2mqtt"
    frigate:
      ansible_user: "root"
      ansible_host: "pve-frigate"

  children:
    workstations:
      hosts:
        serenity:
        nova:
    servers:
      hosts:
        luna:
        monitor:
        pve:
    vms:
      hosts:
        monitor:
    zfs:
      hosts:
        luna:
        serenity:
        nova:
        pve:
    debian:
      hosts:
        monitor:
        netmon:
        pve:
        pve-router:
        caddy:
        vaultwarden:
        postgresql:
        mqtt:
        zigbee2mqtt:
        frigate:
    lxc:
      hosts:
        pve-router:
        caddy:
        vaultwarden:
        postgresql:
        mqtt:
        zigbee2mqtt:
        frigate:
