---
- name: "common:journald:config_dir:create"
  ansible.builtin.file:
    path: "/etc/systemd/journald.conf.d"
    state: "directory"
    mode: "0755"

- name: "common:journald:configure"
  ansible.builtin.template:
    src: "etc/systemd/journald.conf.d/00-ansible.conf.j2"
    dest: "/etc/systemd/journald.conf.d/00-ansible.conf"
    mode: "0644"
  notify: "common:journald|restart"

- name: "common:systemd:config_dir:create"
  ansible.builtin.file:
    path: "/etc/systemd/system.conf.d"
    state: "directory"
    mode: "0755"

- name: "common:systemd:configure"
  ansible.builtin.template:
    src: "etc/systemd/system.conf.d/00-ansible.conf.j2"
    dest: "/etc/systemd/system.conf.d/00-ansible.conf"
    mode: "0644"
  notify: "common:systemd|daemon-reexec"

- name: "common:resolved:config_dir:create"
  ansible.builtin.file:
    path: "/etc/systemd/resolved.conf.d"
    state: "directory"
    mode: "0755"
  when: "systemd_resolved_enabled"

- name: "common:resolved:configure"
  ansible.builtin.template:
    src: "etc/systemd/resolved.conf.d/00-ansible.conf.j2"
    dest: "/etc/systemd/resolved.conf.d/00-ansible.conf"
    mode: "0644"
  notify: "common:resolved|restart"
  when: "systemd_resolved_enabled"
