---
- name: "systemd:journald:config_dir:create"
  ansible.builtin.file:
    path: "/etc/systemd/journald.conf.d"
    state: "directory"
    mode: "0755"

- name: "systemd:journald:configure"
  ansible.builtin.template:
    src: "etc/systemd/journald.conf.d/00-ansible.conf.j2"
    dest: "/etc/systemd/journald.conf.d/00-ansible.conf"
    mode: "0644"
  notify: "systemd:journald|restart"

- name: "systemd:config_dir:create"
  ansible.builtin.file:
    path: "/etc/systemd/system.conf.d"
    state: "directory"
    mode: "0755"

- name: "systemd:configure"
  ansible.builtin.template:
    src: "etc/systemd/system.conf.d/00-ansible.conf.j2"
    dest: "/etc/systemd/system.conf.d/00-ansible.conf"
    mode: "0644"
  notify: "systemd:systemd|daemon-reexec"

- name: "systemd:resolved:config_dir:create"
  ansible.builtin.file:
    path: "/etc/systemd/resolved.conf.d"
    state: "directory"
    mode: "0755"
  when: "systemd_resolved_enabled"

- name: "systemd:resolved:configure"
  ansible.builtin.template:
    src: "etc/systemd/resolved.conf.d/00-ansible.conf.j2"
    dest: "/etc/systemd/resolved.conf.d/00-ansible.conf"
    mode: "0644"
  notify: "systemd:resolved|restart"
  when: "systemd_resolved_enabled"
