---
apt_unattended_upgrades_origins:
  - "origin=Debian,codename=${distro_codename}-updates"
  - "origin=Docker,codename=${distro_codename},label=Docker CE"
  - "origin=Tailscale,codename=${distro_codename},label=Tailscale"
  - "origin=apt.postgresql.org,codename=${distro_codename}-pgdg,label=PostgreSQL for Debian/Ubuntu repository"
  - "origin=cloudsmith/caddy/stable,codename=${distro_codename}"
