---
zfs_scrub_pools:
  - "luna"
  - "luna-data"

zfs_trim_pools:
  - "luna"

zfs_scrub_schedule: "Mon *-*-* 0:00"
zfs_trim_schedule: "Tue *-*-* 0:00"

sysctl_vars:
  - name: "net.bridge.bridge-nf-call-arptables"
    value: 0
    comment: "https://serverfault.com/questions/963759/docker-breaks-libvirt-bridge-network + https://wiki.libvirt.org/page/Net.bridge.bridge-nf-call_and_sysctl.conf"

  - name: "net.bridge.bridge-nf-call-ip6tables"
    value: 0
    comment: "https://serverfault.com/questions/963759/docker-breaks-libvirt-bridge-network + https://wiki.libvirt.org/page/Net.bridge.bridge-nf-call_and_sysctl.conf"

  - name: "net.bridge.bridge-nf-call-iptables"
    value: 0
    comment: "https://serverfault.com/questions/963759/docker-breaks-libvirt-bridge-network + https://wiki.libvirt.org/page/Net.bridge.bridge-nf-call_and_sysctl.conf"

  - name: "net.core.rmem_max"
    value: 7500000

  - name: "net.core.wmem_max"
    value: 7500000
