---
- name: sysctl:config_dir:create
  ansible.builtin.file:
    path: /etc/sysctl.d/
    state: directory
    mode: "0755"

- name: sysctl:configure
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value | default('') }}"
    state: "{{ item.state | default('present') }}"
    sysctl_file: /etc/sysctl.d/90-ansible.conf
    sysctl_set: true
  loop: "{{ sysctl_default_vars | community.general.lists_mergeby(sysctl_vars, 'name') }}"
