---
- name: common.systemd|daemon-reexec # noqa: name[casing]
  ansible.builtin.systemd:
    daemon_reexec: true

- name: common.journald|restart # noqa: name[casing]
  ansible.builtin.service:
    name: systemd-journald
    state: restarted
