---
- name: common:profile:xdg_dirs
  ansible.builtin.template:
    src: etc/profile.d/xdg.sh.j2
    dest: /etc/profile.d/xdg.sh
    mode: "0644"

- name: common:journald:config_dir:create
  ansible.builtin.file:
    path: /etc/systemd/journald.conf.d
    state: directory
    mode: "0755"

- name: common:journald:configure
  ansible.builtin.template:
    src: etc/systemd/journald.conf.d/00-ansible.conf.j2
    dest: /etc/systemd/journald.conf.d/00-ansible.conf
    mode: "0644"
  notify: common:journald|restart

- name: common:systemd:config_dir:create
  ansible.builtin.file:
    path: /etc/systemd/system.conf.d
    state: directory
    mode: "0755"

- name: common:systemd:configure
  ansible.builtin.template:
    src: etc/systemd/system.conf.d/00-ansible.conf.j2
    dest: /etc/systemd/system.conf.d/00-ansible.conf
    mode: "0644"
  notify: common:systemd|daemon-reexec
