---
- name: Configure XDG dirs
  ansible.builtin.template:
    src: profile.d/xdg.sh.j2
    dest: /etc/profile.d/xdg.sh
    mode: "0644"

- name: Ensure /etc/systemd/journald.conf.d exists
  ansible.builtin.file:
    path: /etc/systemd/journald.conf.d
    state: directory
    mode: "0755"

- name: Configure journald
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /etc/systemd/journald.conf.d/{{ item | basename | splitext | first }}
    mode: "0644"
  with_fileglob:
    - templates/etc/systemd/journald.conf.d/*.j2
  notify: common.journald|restart

- name: Ensure /etc/systemd/system.conf.d exists
  ansible.builtin.file:
    path: /etc/systemd/system.conf.d
    state: directory
    mode: "0755"

- name: Configure systemd
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /etc/systemd/system.conf.d/{{ item | basename | splitext | first }}
    mode: "0644"
  with_fileglob:
    - templates/etc/systemd/system.conf.d/*.j2
  notify: common.systemd|daemon-reexec
