---
- name: "msmtp:dependencies:install"
  ansible.builtin.package:
    name: "{{ __msmtp_system_packages[ansible_distribution] }}"

- name: "msmtp:config_dir:create"
  ansible.builtin.file:
    path: "{{ msmtp_config_file | dirname }}"
    recurse: true
    state: "directory"

- name: "msmtp:configure"
  ansible.builtin.template:
    src: "msmtp/config.j2"
    dest: "{{ msmtp_config_file }}"
    mode: "0640"
