---
- name: Install required system package(s)
  ansible.builtin.package:
    name: "{{ _distro_packages[ansible_distribution | lower] }}"
  vars:
    _distro_packages:
      gentoo:
        - mail-mta/msmtp
        - mail-client/mailx
        - app-misc/ca-certificates
      debian:
        - msmtp
        - msmtp-mta
        - bsd-mailx
        - ca-certificates

- name: Get sendmail version
  ansible.builtin.command:
    cmd: sendmail --version
  register: sendmail_version
  changed_when: false

- name: Ensure sendmail wraps msmtp
  ansible.builtin.assert:
    that: "'msmtp' in sendmail_version.stdout_lines[0]"

- name: Ensure msmtp config directory exists
  ansible.builtin.file:
    path: /root/.config/msmtp
    recurse: true
    state: directory

- name: Configure msmtp
  ansible.builtin.template:
    src: msmtp/config.j2
    dest: /root/.config/msmtp/config
    mode: "0640"

- name: Ensure msmtp is the default mta in mail.rc
  ansible.builtin.lineinfile:
    path: /etc/mail.rc
    regexp: ^set mta=/usr/bin/msmtp$
    line: set mta=/usr/bin/msmtp
