---
- name: tgsend:dependencies:install
  ansible.builtin.package:
    name: "{{ _distro_packages[ansible_distribution | lower] }}"
  vars:
    _distro_packages:
      gentoo:
        - dev-python/virtualenv
      debian:
        - virtualenv

- name: tgsend:install
  ansible.builtin.pip:
    name: telegram-send
    state: latest
    virtualenv: "{{ tgsend_virtualenv }}"

- name: tgsend:symlink:parent_dir:create
  ansible.builtin.file:
    path: /usr/local/bin
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: tgsend:symlink:create
  ansible.builtin.file:
    src: "{{ tgsend_virtualenv }}/bin/telegram-send"
    dest: /usr/local/bin/telegram-send
    state: link
    owner: root
    group: root

- name: tgsend:configure
  ansible.builtin.template:
    src: telegram-send.conf.j2
    dest: /etc/telegram-send.conf
    owner: root
    group: root
    mode: "0640"
  when: tgsend_bot_token and tgsend_chat_id
  notify: tgsend|test
