---
- name: Install virtualenv system package
  ansible.builtin.include_tasks:
    file: "packages/{{ ansible_distribution | lower }}.yml"

- name: Install telegram-send
  ansible.builtin.pip:
    name: telegram-send
    state: latest
    virtualenv: "{{ tgsend_virtualenv }}"
    virtualenv_python: "{{ tgsend_virtualenv_python }}"

- name: Ensure /usr/local/bin exists
  ansible.builtin.file:
    path: /usr/local/bin
    state: directory
    group: root
    owner: root
    mode: "0755"

- name: Create a symlink to /usr/local/bin
  ansible.builtin.file:
    src: "{{ tgsend_virtualenv }}/bin/telegram-send"
    dest: "/usr/local/bin/telegram-send"
    group: root
    owner: root
    state: link

- name: Configure telegram-send
  ansible.builtin.template:
    src: telegram-send.conf.j2
    dest: /etc/telegram-send.conf
    owner: root
    group: root
    mode: "0640"
  when: tgsend_bot_token and tgsend_chat_id
