---
- name: Install required system package(s)
  ansible.builtin.package:
    name: "{{ _distro_packages[ansible_distribution | lower] }}"
  vars:
    _distro_packages:
      gentoo:
        - dev-python/virtualenv
      debian:
        - virtualenv

- name: Install telegram-send # noqa: package-latest
  ansible.builtin.pip:
    name: telegram-send
    state: latest
    virtualenv: "{{ tgsend_virtualenv }}"
    virtualenv_python: "{{ tgsend_virtualenv_python }}"

- name: Ensure /usr/local/bin exists
  ansible.builtin.file:
    path: /usr/local/bin
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create a symlink to /usr/local/bin
  ansible.builtin.file:
    src: "{{ tgsend_virtualenv }}/bin/telegram-send"
    dest: "/usr/local/bin/telegram-send"
    state: link
    owner: root
    group: root

- name: Configure telegram-send
  ansible.builtin.template:
    src: telegram-send.conf.j2
    dest: /etc/telegram-send.conf
    owner: root
    group: root
    mode: "0640"
  when: tgsend_bot_token and tgsend_chat_id
  notify: tgsend|test
