---
- name: "Apply common configuration"
  hosts: "all"
  roles:
    - "common"
    - "systemd"

- name: "Apply sysctl configuration"
  hosts: "all,!netmon"
  roles:
    - "sysctl"

- name: "Set up msmtp"
  hosts: "all"
  roles:
    - "msmtp"

- name: "Set up apt unattended-upgrades and listchanges"
  hosts: "debian"
  roles:
    - "apt-unattended-upgrades"

- name: "Set up telegram-send"
  hosts: "zfs"
  roles:
    - "uv"
    - "telegram-send"

- name: "Set up ZFS maintenance and alerts"
  hosts: "zfs"
  roles:
    - "zfs-maintenance"
