---
- name: "Apply common configuration"
  hosts: "all"
  roles:
    - "common"
    - "sysctl"

- name: "Install uv"
  hosts: "all"
  roles:
    - "uv"

- name: "Set up msmtp"
  hosts: "all"
  roles:
    - "msmtp"

- name: "Set up telegram-send"
  hosts: "all"
  roles:
    - "telegram-send"

- name: "Set up ZFS maintenance systemd units"
  hosts: "zfs"
  roles:
    - "zfs-maintenance"
