---
- name: Apply common configuration to all nodes
  hosts: all
  roles:
    - common
    - sysctl

- name: Set up msmtp as default mta
  hosts: all
  roles:
    - msmtp

- name: Set up ZFS maintenance
  hosts: zfs
  roles:
    - zfs-maintenance

- name: Set up telegram-send
  hosts: all
  roles:
    - telegram-send
